name: Padletアーカイブ一括取得 3

on:
  schedule:
    # 毎時20分と50分に実行
    - cron: '20,50 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-archives:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python環境のセットアップと実行
        run: |
          # タイムゾーンを日本時間に設定
          export TZ='Asia/Tokyo'
          
          # メインの処理をPythonで実行
          # github.event_nameを引数として渡し、待機時間をコントロール
          python3 main.py ${{ github.event_name }}

      - name: まとめて保存
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          
          # archiveフォルダと info.json を追加
          git add archive/ info.json
          
          if git diff --staged --quiet; then
            echo "変更がなかったので保存しません"
          else
            git commit -m "アーカイブデータとメタデータを一括更新"
            git pull origin main --rebase
            git push
          fi
